site_name: CheatSheets
theme:
  name: material
  features:
    - admonition
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - pymdownx.details
    - pymdownx.superfences
    - search.highlight
    - search.suggest

    # - navigation.sections
    # - toc.integrate
    # - navigation.top

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

# plugins:
# - social
# - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/8ft0
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/8ft0
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/janvarga/    


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji

copyright: |
  &copy; 2024 <a href="https://github.com/8ft0"  target="_blank" rel="noopener">8ft0.com</a>