site_name: CheatSheets
theme:
  name: material
  # features:
  #   - navigation.tabs
  #   - navigation.sections
  #   - toc.integrate
  #   # - navigation.top
  #   - search.suggest
  #   - search.highlight
  #   - content.tabs.link
  #   - content.code.annotation
  #   - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

# plugins:
# - social
# - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/8ft0
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/8ft0
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/janvarga/    


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji

copyright: |
  &copy; 2024 <a href="https://github.com/8ft0"  target="_blank" rel="noopener">8ft0</a>